---
- name: Install Intelmq with ELK stack.
  hosts: all 
  remote_user: vagrant
  sudo: yes

  roles:
    - common
    - nginx
    - php5-fpm
    - java 
    - elasticsearch
    - logstash
    - kibana
    - intelmq
    - intelmq-manager

