---
- name: Clone intelmq repo
  git: repo=git://github.com/ezeteze/intelmq.git
       dest=/tmp/intelmq
  sudo: yes

- name: pip install intelmq
  shell: 'pip install /tmp/intelmq/'

- name: Add intelmq group
  group: name=intelmq state=present
  sudo: yes

- name: Add intelmq user
  user: name=intelmq group=intelmq
  sudo: yes

- name: Set proper permissions
  file: path=/opt/intelmq owner=intelmq group=intelmq mode=0770 state=directory recurse=yes
  sudo: yes
