---
- name: Clone intelmq repo
  git: repo=https://github.com/ezeteze/intelmq dest=/tmp/intelmq
  sudo: yes

- name: pip install intelmq
  shell: 'yes | pip install /tmp/intelmq'

- name: Add intelmq group
  group: name=intelmq state=present
  sudo: yes

- name: Add intelmq user
  user: name=intelmq group=intelmq home=/opt/intelmq
  sudo: yes
  
- name: Install requirements from pip
  pip: name={{ item }}
  with_items: pip_requirements
  sudo: yes

- name: Set proper permissions
  file: path=/opt/intelmq owner=intelmq group=intelmq mode=0770 state=directory recurse=yes
  sudo: yes
